#cloud-config
write_files:
  - path: /etc/sysconfig/docker
    content: |
      OPTIONS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock"

runcmd:
  - yum update -y
  - curl -fsSL https://get.docker.com/ | sh
  - service docker start
  - export EC2_PUBLIC_HOSTNAME=`curl http://169.254.169.254/latest/meta-data/public-hostname`
