#cloud-config
runcmd:
  - yum update -y
  - curl -fsSL https://get.docker.com/ | sh
  - service docker start
  - export EC2_PRIVATE_IPV4=`curl http://169.254.169.254/latest/meta-data/local-ipv4`
  - docker run -d -p 8300:8300 -p 8301:8301 -p 8301:8301/udp -p 8302:8302 -p 8302:8302/udp -p 8400:8400 -p 8500:8500 -p 8600:8600/udp --name=consul --restart=always progrium/consul -server -advertise $${EC2_PRIVATE_IPV4} -bootstrap-expect ${consul_server_count} -join=10.0.0.24
