#cloud-config
write_files:
  - path: /etc/systemd/system/docker.service.d/docker.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock
  - path: /etc/yum.repos.d/docker.repo
    content: |
      [dockerrepo]
      name=Docker Repository
      baseurl=https://yum.dockerproject.org/repo/main/centos/7/
      enabled=1
      gpgcheck=1
      gpgkey=https://yum.dockerproject.org/gpg

runcmd:
  - yum install -y epel-release
  - yum update -y
  - yum install -y python-pip docker-engine
  - pip install --upgrade pip awscli
  - service docker start
  - export EC2_PRIVATE_IPV4=`curl http://169.254.169.254/latest/meta-data/local-ipv4`
  - export EC2_PUBLIC_HOSTNAME=`curl http://169.254.169.254/latest/meta-data/public-hostname`
