---
- name: ensure that apt works with the https method
  apt:
    name: apt-transport-https
    state: present

- name: install docker GPG key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: add docker apt repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main
    state: present

- name: install docker engine
  apt:
    name: docker-engine
    state: present
