#!groovy

def appDir = 'creating-docker-containers-with-ansible-demo/tripler-tracker'

node('docker && nodejs') {
  wrap([$class: 'AnsiColorBuildWrapper', colorMapName: 'xterm']) {
    stage 'Checkout'
    checkout scm

    stage 'Build'
    dir(appDir) {
      // clean up older images
      sh '''#!/bin/sh
        [ $(uname -s) != "Darwin" ] && alias xargs="xargs --no-run-if-empty"
        docker ps -q -f status=exited | uniq | xargs docker rm -f
        docker images -q "redis*" | uniq | xargs docker rmi -f
        docker images -q "tripler*" | uniq | xargs docker rmi -f
      '''
      // build a fresh image
      sh 'ansible-container build -e ANSIBLE_FORCE_COLOR=1'
    }

    stage 'Test'
    dir(appDir) {
      try {
        sh 'ansible-container run --detached --production'
        sh 'make test'
      } catch (e) {
        throw e
      } finally {
        sh 'ansible-container stop'
      }
    }

    stage 'Release'
    dir(appDir) {
      sh 'ansible-container push'
    }
  }
}
