version: "2"
services:
  app:
    build:
      context: .
    image: tripler-tracker:docker-compose
    ports:
      - 8888:8888
    command: ["node", "/src/app.js"]
    links:
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
