#!groovy

def projectDir = 'creating-docker-containers-with-ansible-demo/tripler-tracker'

stage 'Build'
node('docker-for-mac') {
  deleteDir()
  checkout scm
  dir(projectDir) {
    sh 'ansible-container build -e ANSIBLE_FORCE_COLOR=1'
  }
  stash 'sources'
}

stage 'Test'
node('nodejs') {
  deleteDir()
  unstash 'sources'
  dir(projectDir) {
    try {
      sh 'ansible-container run --detached --production'
      sh 'make test'
    } catch (e) {
      throw e
    } finally {
      sh 'ansible-container stop'
    }
  }
}

stage 'Release'
node('docker-for-mac') {
  deleteDir()
  unstash 'sources'
  dir(projectDir) {
    sh 'ansible-container push'
  }
}
