#!groovy

def appDir = 'tripler-tracker'

stage 'Build'
node('docker-for-mac') {
  deleteDir()
  checkout scm
  dir(projectDir) {
    sh '''
      source venv/bin/activate
      ansible-container build -e ANSIBLE_FORCE_COLOR=1
    '''
  }
  stash 'sources'
}

stage 'Test'
node('nodejs') {
  deleteDir()
  unstash 'sources'
  dir(appDir) {
    try {
      sh '''
        source venv/bin/activate
        ansible-container run --detached --production
        make test
      '''
    } catch (e) {
      throw e
    } finally {
      sh '''
        source venv/bin/activate
        ansible-container stop
      '''
    }
  }
}

stage 'Release'
node('docker-for-mac') {
  deleteDir()
  unstash 'sources'
  dir(appDir) {
    sh 'ansible-container push'
  }
}
